In [2]:
import torch

In [30]:
idx = torch.randn((3,4))
block_size =2
print(idx)



tensor([[-0.3772, -0.9121,  1.0657,  0.4292],
        [-0.4530,  1.9046,  0.1726,  0.2308],
        [-0.3237, -1.4366, -0.7782, -1.2020]])


In [31]:
print(idx[:, -1:])

tensor([[ 0.4292],
        [ 0.2308],
        [-1.2020]])


In [9]:
print(idx[:, 1:])

tensor([[[ 2.4433, -0.1172,  0.8518, -0.8324,  0.7827],
         [-0.7824,  2.2360,  1.5032, -0.1692,  1.4627],
         [ 0.7133,  0.0896, -0.0311,  0.7539, -0.4452]],

        [[-0.8244, -0.4705,  1.1765, -2.4396, -1.3097],
         [ 1.7844,  0.1692,  0.1082,  0.4637, -0.5365],
         [ 0.5586,  1.4038,  0.9603, -0.4364,  0.8677]],

        [[ 0.1854, -0.2607, -1.0432,  0.0247, -1.5309],
         [-0.8444, -2.1971, -2.0088,  0.6204,  1.1548],
         [-0.2947, -0.9316,  0.4653, -0.2065,  0.6638]]])


In [10]:
a = torch.randn((3))

In [17]:
print(a)
print(a[1])
print(a[1:])
print(a[:-1])
print(a[:2])

tensor([-0.3215,  0.5386, -0.5245])
tensor(0.5386)
tensor([ 0.5386, -0.5245])
tensor([-0.3215,  0.5386])
tensor([-0.3215,  0.5386])


In [18]:
b = torch.randn((3,4))

In [21]:
print(b)
print(b[1])
print(b[1:])

tensor([[ 1.2766, -0.7999, -2.0364,  0.8804],
        [-1.1129, -0.6584, -0.4914, -1.3118],
        [ 0.8225,  0.2058,  0.2323, -1.5200]])
tensor([-1.1129, -0.6584, -0.4914, -1.3118])
tensor([[-1.1129, -0.6584, -0.4914, -1.3118],
        [ 0.8225,  0.2058,  0.2323, -1.5200]])


In [22]:
print(b[1,1:3])

tensor([-0.6584, -0.4914])


In [28]:
print(b[:,-1:])

tensor([[ 0.8804],
        [-1.3118],
        [-1.5200]])


In [29]:
print(b[:,3:])

tensor([[ 0.8804],
        [-1.3118],
        [-1.5200]])
